project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true

website:
  title: "MIMEE"
  description: "Modular Instrument for Music-related Emotional Episodes"
  repo-url: https://github.com/tuomaseerola/MIMEE/
#  repo-actions: [source, edit, issue]
  site-url: "https://tuomaseerola.github.io/MIMEE/"
  search: true
  navbar:
    left:
      - href: index.qmd
#        text: Home
      - icon: github
        href: https://github.com/tuomaseerola/MIMEE/
        aria-label: GitHub
  page-navigation: true
  back-to-top-navigation: true
#  sidebar:
#    - title: "Home"
#      style: "floating"
#      collapse-level: 3
#      align: left
#      contents: 
#          - text: "Home"
#            href: index.qmd
#          - section: "Analysis"
#            contents:
#                - item_analysis.qmd
#                - expert_eval_round1.qmd
#                - expert_eval_round2.qmd
#                - expert_eval_round2_repr.qmd
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/tuomaseerola/
format:
  html:
    theme: materia # zephyr, lumen, pulse, materia, yeti, zephyr
    css: styles.css
    toc: true
    page-layout: full
