---
title: "Modular Instrument for Music-related Emotional Episodes – Assessment of the content validity of the episode model"
author:
  - name: Connor Kirts
    orcid: 0009-0009-7207-6884
    email: connor.kirts@durham.ac.uk
    affiliations:
      - name: Durham University, UK
  - name: Suvi Saarikallio
    orcid: 0000-0002-4647-8048
    email: suvi.saarikallio@jyu.fi
    affiliations:
      - name: University of Jyväskylä, Finland
  - name: Tuomas Eerola
    orcid: 0000-0002-2896-929X
    email: tuomas.eerola@durham.ac.uk
    affiliations:
      - name: Durham University, UK
date: 5-5-2025
title-block-style: default
---

This repository offers data and analyses related to the study titled "Measuring emotional experiences of music – Assessment of the content validity of the episode model" by Kirts et al., (in preparation). The data is about an instrument to measure a recent theory concerning emotional episodes related to music ([Eerola, Kirts & Saarikallio, 2024](https://doi.org/10.1177/03057356241279763)).

The public-facing version of the repository is available at
[https://tuomaseerola.github.io/MIMEE/](https://tuomaseerola.github.io/MIMEE/). At the moment we call the instrument _Modular Instrument for Music-related Emotional Episodes_ (MIMEE).

Three main analytical operations are documented here.

## Semantic similarity analysis

- [Item similarity analysis](item_analysis.qmd) was used to trim the number of items from 495 to 336.
- [Item similarity visualisation](item_similarity_visualisation.qmd) shows the output of the analysis.

## Expert evaluations: round 1

- [Expert Evaluations: Round 1](expert_eval_round1.qmd) contains the analysis of all proposed items by 14 subject matter specialists.
- [Item decisions](item_decisions.qmd) contains a long summary concerning item details and feedback from the experts.

## Expert evaluations: round 2

- [Expert Evaluations: Round 2](expert_eval_round2.qmd) contains the analysis of all proposed items by 14 subject matter specialists.
- [Expert Evaluations: Round 2 representativeness](expert_eval_round2_repr.qmd) contains the analysis of representative items as denoted by subject matter specialists.
- [Expert Evaluations: Round 2 representativeness - Table 4](generate_table4.qmd) contains the top N (2 at the moment) representative items for each sub-construct.

## References

- Eerola, T., Kirts, C., & Saarikallio, S. (2024). Episode model: The functional approach to emotional experiences of music. _Psychology of Music, 0(0)_. [https://doi.org/10.1177/03057356241279763](https://doi.org/10.1177/03057356241279763)